FROM c.rzp.io/razorpay/rzp-docker-image-inventory-multi-arch:rzp-golden-image-base-golang-1.24-alpine3.21

RUN apk add git

# Create a temporary directory for Git to use as its configuration directory
RUN mkdir -p /gitconfig && \
    chmod 777 /gitconfig

# Set Git's configuration directory to the temporary directory
ENV HOME /gitconfig