apiVersion: apps/v1
kind: Deployment
metadata:
  name: day5
  namespace: day5
  labels:
    app: day5
  annotations:
    janitor/ttl: "71h"  # 7 days
spec:
  replicas: 3
  selector:
    matchLabels:
      app: day5
  template:
    metadata:
      labels:
        app: day5
    spec:
      containers:
      - name: day5
        image: day5:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: SERVER_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: SERVER_HOST
        - name: SERVER_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: SERVER_PORT
        - name: ENV
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: ENV
        - name: DATABASE_DIALECT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DATABASE_DIALECT
        - name: DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DATABASE_HOST
        - name: DATABASE_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DATABASE_PORT
        - name: DATABASE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DATABASE_USERNAME
        - name: DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DATABASE_NAME
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: DATABASE_PASSWORD
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
