apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: day5
  labels:
    app: mysql
    devstack_label: "mysql-service"
spec:
  ports:
  - port: 3306
    protocol: TCP
  selector:
    app: mysql
