apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
    {{- include "day5.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
    name: mysql
  selector:
    app: mysql
