apiVersion: v1
kind: Service
metadata:
  name: {{ include "day5.fullname" . }}
  labels:
    {{- include "day5.labels" . | nindent 4 }}
    devstack_label: "day5-service"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "day5.selectorLabels" . | nindent 4 }}
