[app]
  env = "default"
  serviceName = "payment"
  hostname = "payment.example.com"
  logger = "zap"

[server]
  [server.Addresses]
      http  = ":8080"
      grpc  = ":8081"
  shutdowntimeout = 10

[store]
  choice = "sql"
  ormChoice = "gorm"
  # [store.SQL]
      # dialect = "postgres"
      # protocol = ""
      # url = "postgres"
      # port = 5432
      # username = "payment_user"
      # password = "payment_pass"
      # sslmode = "disable"
      # name = "payment"
      # schema = "payment"
      # charset = ""
      # maxopenconnections = 10
      # maxidleconnections = 5
      # connectionmaxlifetime = "120"
      # debug = true 
  [store.SQL]
      dialect = "mysql"
      protocol = "tcp"
      url = "mysql"
      port = 3306
      username = "payment_user"
      password = "payment_pass"
      sslmode = "disable"
      name = "payment"
      schema = "payment"
      charset = "utf8mb4"
      maxopenconnections = 10
      maxidleconnections = 5
      connectionmaxlifetime = "120"
      debug = true 
