name: build_example
on:
  push:
    branches:
      - master
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

env:
  REGISTRY: c.rzp.io/razorpay
  IMAGE_PREFIX: go-foundation-v2-

jobs:
  push:
    strategy:
      matrix:
        go-version-file: 'go.mod'
        platform:
          - linux-amd64
          - linux-arm64
    runs-on:
      - self-hosted
      - non-api
      - ${{ matrix.platform }}
    env:
      GOPRIVATE: github.com/razorpay
      HOME: '/home/runner'
      DOCKER_BUILDKIT: 1
    steps:
      - uses: razorpay/create-github-app-token@v1
        name: Generate Github Token
        id: app-token
        with:
          app-id: ${{ secrets.WORKFLOWGATEKEEPER_APP_ID }}
          private-key: ${{ secrets.WORKFLOWGATEKEEPER_PRIVATEKEY }}
          repositories: 'goutils,upi-switch,go-foundation-v2,rpc'
      - name: Login to Harbor
        id: login_harbor
        run: |
          for i in {1..3}; do
            echo "Attempt $i to login to Harbor"
            docker login c.rzp.io -u ${{ secrets.HARBOR_DOCKER_USERNAME }} -p ${{ secrets.HARBOR_DOCKER_PASSWORD }} && break
            echo "Login attempt $i failed, retrying in 10 seconds..."
            sleep 10
          done
        shell: bash
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Verify BuildKit
        run: |
          echo "Docker BuildKit status: $DOCKER_BUILDKIT"
          docker buildx version
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Set Git for Private
        env:
          TOKEN: ${{ steps.app-token.outputs.token }}
        run: git config --global url."https://x-access-token:${TOKEN}@github.com".insteadOf "https://github.com"
      - uses: extractions/netrc@v1
        with:
          machine: github.com
          username: rzp
          password: ${{ steps.app-token.outputs.token }}
      - name: Push image
        env:
          TOKEN_GIT: ${{ steps.app-token.outputs.token }}
          REGISTRY: ${{ env.REGISTRY }}
          BINS: example
        run: |
          retries=3
          for i in $(seq 1 $retries); do
            if make push; then
              echo "Push successful on attempt $i"
              break
            else
              echo "Push failed on attempt $i"
              if [ $i -eq $retries ]; then
                exit 1
              fi
              sleep 10
            fi
          done
  push-migration:
    strategy:
      matrix:
        go-version-file: 'go.mod'
        platform:
          - linux-amd64
          - linux-arm64
    runs-on:
      - self-hosted
      - non-api
      - ${{ matrix.platform }}
    env:
      GOPRIVATE: github.com/razorpay
      HOME: '/home/runner'
      DOCKER_BUILDKIT: 1
    steps:
      - uses: razorpay/create-github-app-token@v1
        name: Generate Github Token
        id: app-token
        with:
          app-id: ${{ secrets.WORKFLOWGATEKEEPER_APP_ID }}
          private-key: ${{ secrets.WORKFLOWGATEKEEPER_PRIVATEKEY }}
          repositories: 'goutils,upi-switch,go-foundation-v2,rpc'
      - name: Login to Harbor
        id: login_harbor
        run: |
          for i in {1..3}; do
            echo "Attempt $i to login to Harbor"
            docker login c.rzp.io -u ${{ secrets.HARBOR_DOCKER_USERNAME }} -p ${{ secrets.HARBOR_DOCKER_PASSWORD }} && break
            echo "Login attempt $i failed, retrying in 10 seconds..."
            sleep 10
          done
        shell: bash
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Verify BuildKit
        run: |
          echo "Docker BuildKit status: $DOCKER_BUILDKIT"
          docker buildx version
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Set Git for Private
        env:
          TOKEN: ${{ steps.app-token.outputs.token }}
        run: git config --global url."https://x-access-token:${TOKEN}@github.com".insteadOf "https://github.com"
      - uses: extractions/netrc@v1
        with:
          machine: github.com
          username: rzp
          password: ${{ steps.app-token.outputs.token }}
      - name: Push image - example migration
        env:
          TOKEN_GIT: ${{ steps.app-token.outputs.token }}
          REGISTRY: ${{ env.REGISTRY }}
          BINS: example_migration
        run: |
          retries=3
          for i in $(seq 1 $retries); do
            if make push; then
              echo "Push successful on attempt $i"
              break
            else
              echo "Push failed on attempt $i"
              if [ $i -eq $retries ]; then
                exit 1
              fi
              sleep 10
            fi
          done
  push-combined-all:
    # This action combines the amd64 & arm64 docker images from the previous job & forms a multi-arch docker image for all binaries
    needs: [push, push-migration]
    strategy:
      matrix:
        binary:
          - example
          - example_migration
    name: Build Multiarch ${{ matrix.binary }}
    runs-on:
      - self-hosted
      - non-api
      - X64
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: c.rzp.io
          username: ${{ secrets.HARBOR_DOCKER_USERNAME }}
          password: ${{ secrets.HARBOR_DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create Docker Manifest
        uses: int128/docker-manifest-create-action@v2
        with:
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}${{ matrix.binary }}:${{ github.event.pull_request.head.sha || github.sha }}
          sources: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}${{ matrix.binary }}:linux-amd64-${{ github.event.pull_request.head.sha || github.sha }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}${{ matrix.binary }}:linux-arm64-${{ github.event.pull_request.head.sha || github.sha }}

  workflow_status:
    runs-on:
      - self-hosted
      - non-api
      - X64
    name: Update Status Check
    needs: [push-combined-all]
    if: always()
    steps:
      - name: Failed
        id: failed
        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
        run: |
          echo 'Failing the workflow for github status check.'
          curl -X POST -H "Content-Type: application/json" -H "Authorization: token ${{ github.token }}" \
          -d '{ "state" : "failure" , "context" : "github/combined-status-check" , "description" : "github/combined-status-check", "target_url" : "https://github.com/${{ github.repository }}" }' \
          https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.event.pull_request.head.sha || github.sha }}
          exit 1
      - name: Success
        if: steps.failed.conclusion == 'skipped'
        run: |
          echo 'Status check has passed!'
          curl -X POST -H "Content-Type: application/json" -H "Authorization: token ${{ github.token }}" \
          -d '{ "state" : "success" , "context" : "github/combined-status-check" , "description" : "github/combined-status-check", "target_url" : "https://github.com/${{ github.repository }}" }' \
          https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.event.pull_request.head.sha || github.sha }}
          exit 0
